### ISSUE TITLE
Adding CSS to an extension

### ISSUE THREAD

**Issue by michzimny** [jupyterlab/extension-cookiecutter-js#23]
Hello, how could I add a CSS file to an extension built based on this repo?

I have found examples for typescript extension only. Could you please refer an example or docs for this cookiecutter?

**Comment by michzimny** [comment]
Ok, this is a working example I have deduced: https://github.com/jupyterlab/extension-cookiecutter-js/pull/24

Is it how it should be done?

**Comment by vidartf** [comment]
Closed in #24.
