### ISSUE TITLE
Issue generating working plugin.js using webpack

### ISSUE THREAD

**Issue by nscozzaro** [jupyterlab/extension-cookiecutter-js#27]
**What works:** using the cookiecutter to generate a working extension.
**What I'm trying to do but can't get to work:** generate a working `plugin.js` file using webpack, so that I can use libraries such as Vue.js in the extension. 
**To reproduce:** (1) create a cookiecutter (2) create a `src` directory with a copy of `plugin.js` (3) install webpack (`npm install webpack webpack-cli --save`) (4) Run `webpack src/plugin.js --output-path lib --output-filename plugin.js` which outputs the bundle as `lib/plugin.js` (5) Run `jupyter labextension link .` then check that there is no output in the JupyterLab js-console as there is supposed to be. If it happened to work, make sure that in `package.json` you have `"main": "lib/plugin.js"` (I originally closed the issue because I forgot that I changed main, so it wasn't using the bundle)
![image](https://user-images.githubusercontent.com/15185105/61174351-daf43800-a56c-11e9-8aeb-3b5579217bcd.png)

Please let me know how I can make this work!

**Comment by bollwyvl** [comment]
Apologies for any difficulties you're having. I [had a look](https://gist.github.com/bollwyvl/4a7c46f6f345293cb6ae7063e5d4c1e9), but unfortunately, the most [promising examples](https://github.com/microsoft/TypeScript-Vue-Starter) are apparently outdated, and I don't know vue!

## For $DAY_JOB
If you're just trying to demonstrate a custom lab for a specific project with limited release, and you or ci are the only ones doing the building, you _might_ try:
- keep doing what you're doing! 
  - We'll try to keep the standard tooling working as well as possible: with the 1.0 release, I assume we are married to `webpack` until at least a 2.0 release.
- try with `vue-loader<15`, which works without the plugin. I also ran into `.vue` issues, but then... I don't know Vue. 

> Definitely getting a lot of
```
 Property or method "name" is not defined on the instance but referenced during render. 
Make sure that this property is reactive, either in the data option, or for class-based 
components, by initializing the property.
```
> with the `Hello.vue`.


## For $SCIENCE
However, if your project is going to be more broadly used (e.g. for science or education) and release on `npm`, I don't think it's really reasonable to set the precedent for forcing extra loaders on every end user. Of course the high-road is getting to where we can package stuff better, but for now, the best we can do is utilize npm, etc. 

### Repo Organization
The approach you might take here would be with multiple packages. JupyterLab itself does this, using `lerna` to manage it. So your repo might look like:

```
- packages/
  - vue-app/
   - webpack.config.ts
   - src/
     - index.ts
     - components/
       - Foo.vue
  - jupyterlab-vue-app/
   - src/
     - plugin.ts
     - widget.ts
```
Where `@my-org/juptyerlab-vue-app` depends on `@my-org/vue-app`, which in turn hides most of the compiled vue machinery, exposing a "clean" commonjs/esnext package.

This would probably have to land in a separate cookiecutter, e.g. `@jupyterlab/extension-cookiecutter-lerna-ts`, with a prompt at run time, e.g.
```
Are you wrapping a component from another framework?
- [x] no
- [ ] angular
- [ ] react
- [ ] vue
- [ ] webcomponent
```
Where we could collect these patterns.

### Runtime
If your Vue app isn't going to be loaded until the user does something, you should definitely try to `await import` your app in your extension, as in my [failed attempt](https://gist.github.com/bollwyvl/4a7c46f6f345293cb6ae7063e5d4c1e9#file-index-ts-L38)

This will keep the size of vue+deps (and any others that you might have) off the bottom line of loading the page. That hello world example cost a pretty penny!
```
-rw-rw-r--. 1 weg weg  34M Jul 12 20:53 vendors~main.ffb1c8912d4afa7f8e4f.js
-rw-rw-r--. 1 weg weg 952K Jul 12 20:53 vendors~example-vue.f3c86b4dcff3dbad8ddc.js
```
(of course, it would be minified and gzipped, but hey, every little bit counts)

A minimal example shared somewhere would help!

**Comment by nscozzaro** [comment]
@bollwyvl thank you very much for giving it a try! 
If all goes well, the extension will be more in the $SCIENCE category. 

I solved one of the main issues: if I add (to the steps above) a step, (6) add `libraryTarget: 'commonjs-module'` to the webpack; the basic extension with the console.log's works. 

However, if I try to use webpack on a more complicated extension with imports, I'm now getting a new error in the browser's JS console, `Error: No provider for: @jupyterlab/apputils:ICommandPalette` that I describe in more detail here, since it seems related to another issue: https://github.com/jupyterlab/jupyterlab-google-drive/issues/19

**Comment by nscozzaro** [comment]
I was able to solve this problem by using webpack-node-externals in my webpack.config.js:

```
var nodeExternals = require('webpack-node-externals');
const VueLoaderPlugin = require('vue-loader/lib/plugin');

module.exports = {
    entry: [
        './src/plugin.js'
    ],
    target: 'node', // in order to ignore built-in modules like path, fs, etc.
    externals: [nodeExternals()],
    output: {
        path: path.resolve(__dirname, 'lib'),
        filename: 'plugin.js',
        libraryTarget: 'commonjs-module'
    },
```

I'm now able to render the hello world vue template. 
![image](https://user-images.githubusercontent.com/15185105/61186421-2244fc00-a633-11e9-9d4a-29f0d4fbc4f6.png)

**Comment by bollwyvl** [comment]
@nscozzaro great! If you can share your stuff at some point, it would be great to have at least a link to a working example!

**Comment by nscozzaro** [comment]
Hey @bollwyvl I cleaned up the code a bit and put together a repository here for a JupyterLab Hello World Vue.js extension: https://github.com/nscozzaro/jupyterlab_vue.

If you get a chance, please try cloning and installing. I'd like to make sure that it works for others!
