### ISSUE TITLE
How to import Widget classes?

### ISSUE THREAD

**Issue by stefaneidelloth** [jupyterlab/extension-cookiecutter-js#30]
I would like to write a JupyterLab Extension in pure Javascript/ES6.

In order to contribute to the left sidebar, I would like to create some custom widget, for example:

```
var myWidget = new MyWidget()
app.shell.add(myWidget, 'left', { rank: 200 });
```

In Typescript I could import some basic widget class to inherit from, for example:

`import { ReactWidget } from '@jupyterlab/apputils';`

Howeever, that does not seem to work in a plain ES6 module without webpack: 

`Uncaught TypeError: Failed to resolve module specifier "@jupyterlab/apputils". Relative references must start with either "/", "./", or "../".`

=>What is the corresponding import path for JavaScript?

Using require would also be fine for me.
Following trials also failed:

`import * as LuminoWidget from '../node_modules/@lumino/widgets/dist/index.es6.js';`

Error:

`Uncaught TypeError: Failed to resolve module specifier "@lumino/algorithm". Relative references must start with either "/", "./", or "../".`

```
require(
['node_modules/@lumino/widgets/dist/index.min'],
function(LuminoWidget){ console.log(LuminoWidget; }
)
```

```
require(
['node_modules/@lumino/widgets/dist/index.es6'],
function(LuminoWidget){ console.log(LuminoWidget; }
)
```
Error:

`require.js:168 Uncaught Error: Script error for "@lumino/algorithm", needed by: node_modules/@lumino/widgets/dist/index.min`

**Comment by jasongrout** [comment]
That syntax should work for plain javascript, assuming you listed `@jupyterlab/apputils` in your package.json as a dependency and installed it with `npm install`.

**Comment by stefaneidelloth** [comment]
I guess, in order to be able to resolve the @foo/baa import aliases, I would need some import magic from a build tool like webpack? Or is there a direct way to tell ES6 where to find those recursively referenced module aliases?

What is the minimal interface a Widget has to implement, so that it correctly works with
JupyterLab methods?

`app.shell.add(myWidget, 'left', { rank: 200 });`

Is there a way to grab a widget class from the JupyterLab instance "app" at runtime?
Or use some kind of factory method to create a basic widget instance?
Something like

```
var widgetClass = app.getBaseWidgetClass();

var widget = app.createWidget('myWidget');
```

**Comment by jasongrout** [comment]
> I guess, in order to be able to resolve the @foo/baa import aliases, I would need some import magic from a build tool like webpack? Or is there a direct way to tell ES6 where to find those recursively referenced module aliases?

npm takes care of all of that for you.

I'd suggest working through the extension tutorial at https://jupyterlab.readthedocs.io/en/stable/developer/extension_tutorial.html, but starting from this js cookiecutter instead of the ts cookiecutter and just ignoring the type annotations (e.g., `activate: (app: JupyterFrontEnd, palette: ICommandPalette) => {` becomes the javascript `activate: (app, palette) => {`)

**Comment by stefaneidelloth** [comment]
Thank you for your help. 
My actual issue was that I was mixing/confusing some concepts. 
What works for me now is to use require in the main file of the JupyterLab extension and inject
the Widget class in the activate method:

```
require('../style/plugin.css');
var { ReactWidget } = require('@jupyterlab/apputils');

module.exports = [{
    id: 'jupyterlab_workspace_module',
    icon: 'fa-comment-o',
    autoStart: true,
     activate: function(app) {
      importES6ModuleViaScriptTag(app, ReactWidget);
    }
}];
...
```

The alias '@jupyterlab/apputils' is resolved during the JupyterLab build step and later I can
use the injected class at runtime.  

(This way I can modify my ES6 extension in the Chrome DevTools and refresh it during
development without needing to rebuild. )
