### ISSUE TITLE
Adopt the new extension distribution system

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/extension-cookiecutter-js#32]
The cookiecutter should already be compatible with 3.0, and the extension can be installed with `jupyter labextension install`.

The main question is whether to adopt the new distribution system. It looks like it would make sense to do it so it's similar to the other cookiecutter: https://github.com/jupyterlab/extension-cookiecutter-ts

**Comment by jasongrout** [comment]
> The main question is whether to adopt the new distribution system. It looks like it would make sense to do it so it's similar to the other cookiecutter: https://github.com/jupyterlab/extension-cookiecutter-ts

+1 - I think we want to encourage and help people to move to the new distribution system.

**Comment by jtpio** [comment]
Funny enough, the cookiecutter seems to have some traces of `_jupyter_labextension_paths` already :) (probably from the first iterations on the extension system in the early days):

https://github.com/jupyterlab/extension-cookiecutter-js/blob/a4305283c5621c7fd737e93b1d53978491099028/%7B%7Bcookiecutter.extension_name%7D%7D/%7B%7Bcookiecutter.extension_name%7D%7D/__init__.py#L5-L9
