### ISSUE TITLE
Rename repo to jupyterlab-extension-cookiecutter-js

### ISSUE THREAD

**Issue by sccolbert** [jupyterlab/extension-cookiecutter-js#7]
As it says on the tin...

**Comment by sccolbert** [comment]
c.f. https://github.com/jupyter/jupyterlab-extension-cookiecutter-ts/issues/1

**Comment by sccolbert** [comment]
cc @jasongrout

**Comment by jasongrout** [comment]
You sure do like tins :).

Done! Thanks.
